name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-cache
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install deps
        run: cd backend && npm i
      - name: Build
        run: cd backend && npm run build
      - name: Generate Artifact
        run: cd backend/build && zip -r artifact.zip ./ -x '*.git*'
      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend/build/artifact.zip
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-cache

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && npm i

      - name: 😂 Lint code
        run: cd backend && npm run lint
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-cache

      - name: Install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && npm i

      - name: Run the unit tests
        run: cd backend && npm t
